services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omniquest
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  backend1:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.docker
    environment:
      RUN_DB_INIT: "true"
    depends_on:
      - db
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  backend2:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.docker
    environment:
      RUN_DB_INIT: "false"
    depends_on:
      - db
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    # env_file:
    #   - frontend/.env.docker
    ports:
      - "5173:80"
    depends_on:
      - nginx

  locust:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: locust -f locustfile.py --host http://nginx:80 --web-host 0.0.0.0
    working_dir: /app
    ports:
      - "8089:8089"
    depends_on:
      - nginx
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
