services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: omniquest
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend1:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.docker
    depends_on:
      - db

  backend2:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - backend/.env.docker
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    # env_file:
    #   - frontend/.env.docker
    ports:
      - "5173:80"
    depends_on:
      - nginx

volumes:
  db_data:


