services:
  devdb:
    build:
      context: .
      dockerfile: db/Dockerfile.dev
    container_name: omniquest-devdb
    ports:
      - "5433:5432"
    volumes:
      - dev_db_data:/var/lib/postgresql/data

volumes:
  dev_db_data:


